### PR TITLE
Fix hvdc model with linear losses - closes #1325

### LINKED ISSUE #1325: HVDC loss model
The HVDC loss model is not functioning correctly. When I applied this linear loss model of HVDC, the HVDC loss was equal to the HVDC flow after solving the Unit Commitment. However, it should be calculated as the linear coefficient multiplied by the HVDC_flow. Please take a look at the results I attached. Thanks a lot.

Image

### PR DESCRIPTION
**Pull request by rbolgaryn**
Modifying the model for losses for TwoTerminalGenericHVDCLine:

```Julia
tf_var[name, t] + ft_var[name, t] == losses[name, t]
losses[name, t] >= l0 + l1 * ft_var[name, t]
losses[name, t] >= l0 + l1 * tf_var[name, t]
losses[name, t] <= l0 + l1 * ft_var[name, t] + M_VALUE * direction_var[name, t]
losses[name, t] <= l0 + l1 * tf_var[name, t] + M_VALUE * (1 - direction_var[name, t])
```

### CODE REVIEW

**Review by rodrigomha — APPROVED** [review]
This looks good for me.

@jd-lara you can merge it if you think it is ok

File: src/devices_models/devices/TwoTerminalDC_branches.jl [hunk 1]
```diff
@@ -833,13 +849,21 @@ function add_constraints!(
...
+                get_jump_model(container),
+                losses[name, t] <=
+                l0 + l1 * ft_var[name, t] + M_VALUE * direction_var[name, t]
+            )
+            constraint_loss_aux4[name, t] = JuMP.@constraint(
+                get_jump_model(container),
+                losses[name, t] <=
+                l0 + l1 * tf_var[name, t] + M_VALUE * (1 - direction_var[name, t])
             )
         end
```
Comment (jd-lara) [inline src/devices_models/devices/TwoTerminalDC_branches.jl:868]: I think there is a return missing here

Comment (rbolgaryn) [reply src/devices_models/devices/TwoTerminalDC_branches.jl:868]: image

Comment (rbolgaryn) [reply src/devices_models/devices/TwoTerminalDC_branches.jl:868]: There is return

Comment (rbolgaryn) [reply src/devices_models/devices/TwoTerminalDC_branches.jl:868]: It was just the diff view showing truncated there
