### PR TITLE
Fix caching behaviors: #1070, #1072, #1074

### LINKED ISSUE #1070: `_read_results` for `Matrix{Float64}` and `DecisionModelSimulationResults` does not use the cache
The implementations of the two `_read_results` methods in [`decision_model_simulation_results.jl`](https://github.com/NREL-Sienna/PowerSimulations.jl/blob/v0.27.4/src/simulation/decision_model_simulation_results.jl) show that one of them checks the cache and the other doesn't. This causes a *vast* difference in the performance of the two methods:

```Julia
# where `res` is a `PowerSimulations.SimulationProblemResults{PowerSimulations.DecisionModelSimulationResults}` with weekly data and a lot of components
julia> timestamps = PSI._process_timestamps(res, DateTime("2035-01-01"), 7);
julia> variables = [PSI.VariableKey(ActivePowerVariable, ThermalStandard)];
julia> load_results!(res, 7; variables=[(ActivePowerVariable, ThermalStandard)]);
julia> @time results_mat = PSI._read_results(Matrix{Float64}, res, variables, timestamps, nothing)
  0.091891 seconds (191.44 k allocations: 15.228 MiB)
Dict{PowerSimulations.OptimizationContainerKey, PowerSimulations.ResultsByTime{Matrix{Float64}}} with 1 entry:
  VariableKey{ActivePowerVariable, ThermalStandard}("") => ResultsByTime{Matrix{Float64}, 1}(VariableKey{ActivePowe…
julia> @time results_jump = PSI._read_results(res, variables, timestamps, nothing)
  0.000150 seconds (133 allocations: 4.953 KiB)
Dict{PowerSimulations.VariableKey{ActivePowerVariable, ThermalStandard}, PowerSimulations.ResultsByTime{JuMP.Containers.DenseAxisArray{Float64, 2, Ax, L} where {Ax, L<:Tuple{JuMP.Containers._AxisLookup, JuMP.Containers._AxisLookup}}, 1}} with 1 entry:
  VariableKey{ActivePowerVariable, ThermalStandard}("") => ResultsByTime{DenseAxisArray{Float64, 2, Ax, L} where {A…
```

The second one becomes as slow as the first if the cache check is commented out. This matters because the first method is what `read_results_with_keys` uses, and therefore this behavior contributes to a lot of slowdown in my PowerAnalytics rewrite, where I call `read_results_with_keys` for each component and need a cache to make this tolerable on large systems.

### PR DESCRIPTION
**Pull request by GabrielKS**
This fixes #1070 and #1072.

## On #1070:
There is some inherent overhead to creating large arrays that cannot be avoided, but now that we use the cache the time for repeated calls to `_read_results(Matrix{Float64}...` on my big dataset has decreased 30x from 0.09s to 0.003s:
```julia
julia> @time results_mat = PSI._read_results(Matrix{Float64}, res, variables, timestamps, nothing)
  0.003551 seconds (340 allocations: 7.419 MiB)
```

This is much better and closes the issue but is still unnecessarily heavy-handed for my PowerAnalytics component-wise reads, so later I may seek to add an option to PowerSimulations to perform `read_results_with_keys` for only one component at a time.

## On #1072:
Ended up being more refactoring than initially planned, but the upshot is that for the `DecisionModelSimulationResults` method of `load_results!` the documentation now precisely describes what happens, what happens is good, the bug preventing it from loading more timestamps is gone, some code duplication has been removed, and there are lots more tests. I did not significantly edit the `EmulationModelSimulationResults` method of `load_results!`; it appears to have a significantly different interface that does not even take in time steps.

```julia
# after the setup detailed in bug #1072
julia> PSI._read_results(res, variable_keys, timestamps, nothing) |> values |> first |> x->x.data |> keys |> collect
7-element Vector{DateTime}:
 2035-01-01T00:00:00
 2035-01-02T00:00:00
 2035-01-03T00:00:00
 2035-01-04T00:00:00
 2035-01-05T00:00:00
 2035-01-06T00:00:00
 2035-01-07T00:00:00
```

### CODE REVIEW

File: src/simulation/realized_meta.jl [hunk 1]
```diff
@@ -69,6 +69,8 @@ function _make_dataframe(
         row_end = row_index + last_id - first_id
         matrix[row_index:row_end, :] = array[first_id:last_id, :]
         row_index += last_id - first_id + 1
+        # Gracefully handle being given more results_by_time than we need
```
Comment (daniel-thom) [inline src/simulation/realized_meta.jl:72]: When does this happen and why isn’t it an error?

File: src/simulation/decision_model_simulation_results.jl [hunk 2]
```diff
@@ -305,20 +254,25 @@ function _process_timestamps(
 end
 
 function _read_results(
-    T::Type{Matrix{Float64}},
+    ::Type{Matrix{Float64}},
     res::SimulationProblemResults{DecisionModelSimulationResults},
     result_keys,
     timestamps::Vector{Dates.DateTime},
-    store::Nothing,
+    store::Union{Nothing, <:SimulationStore},
```
Comment (jd-lara) [inline src/simulation/decision_model_simulation_results.jl:261]: This weird interface relates to #1018 and could be fixed in this PR. @daniel-thom we discussed not doing this anymore.

File: src/simulation/decision_model_simulation_results.jl [hunk 3]
```diff
@@ -90,23 +90,23 @@ get_cached_variables(res::SimulationProblemResults{DecisionModelSimulationResult
 
 get_cached_results(
```
Comment (jd-lara) [inline src/simulation/decision_model_simulation_results.jl:91]: I don't understand why passing the type and not the instance matters here.

File: src/simulation/decision_model_simulation_results.jl [hunk 4]
```diff
@@ -336,12 +290,12 @@ function _read_results(
     end
     existing_keys = list_result_keys(res, first(result_keys))
     _validate_keys(existing_keys, result_keys)
-    cached_results = get_cached_results(res, first(result_keys))
+    cached_results = get_cached_results(res, typeof(first(result_keys)))
```
Comment (jd-lara) [inline src/simulation/decision_model_simulation_results.jl:293]:
```suggestion
    cached_results = get_cached_results(res, eltype(result_keys))
```

Comment (jd-lara) [reply src/simulation/decision_model_simulation_results.jl:293]: This change can be used all over

File: src/simulation/decision_model_simulation_results.jl [hunk 5]
```diff
@@ -622,6 +546,7 @@ function load_results!(
             merge_results(store)
         end
     end
+    res.results_timestamps = new_timestamps
```
Comment (jd-lara) [inline src/simulation/decision_model_simulation_results.jl:549]: make and use a setter for this

**Comment by jd-lara** [comment]
we should put this in the PSY4 branch to avoid massive rebases later. This improvement can wait until the PSY 4 release.

File: src/simulation/decision_model_simulation_results.jl (hunk 2 above)
Comment (GabrielKS) [reply src/simulation/decision_model_simulation_results.jl:261]: I'm not sure exactly what the proposal is here. For now I'm just mimicking the other `_read_results` method and passing the store straight through

File: src/simulation/realized_meta.jl (hunk 1 above)
Comment (jd-lara) [reply src/simulation/realized_meta.jl:72]: This is an interface issue @daniel-thom discussed where we pass a store to read from or nothing when nothing signifies that it is an in-memory store which makes the code confusing since it isn't obvious.

File: src/simulation/decision_model_simulation_results.jl (hunk 3 above)
Comment (GabrielKS) [reply src/simulation/decision_model_simulation_results.jl:91]: Philosophically, it makes more sense to me because we really aren't using any properties of the instance rather than its type. Practically, sometimes we don't necessarily *have* an instance, like [here](https://github.com/NREL-Sienna/PowerSimulations.jl/pull/1073/files/fbfb1ca3d4f1200b0299de04f1a5ef1d49f41a8f#diff-805b5dec2828ffb16a0f459d5e6c31d3f5bf3691a6e1562db8ad6030e81b2ca0R534).

File: src/simulation/decision_model_simulation_results.jl (hunk 2 above)
Comment (jd-lara) [reply src/simulation/decision_model_simulation_results.jl:261]: This is an interface issue @daniel-thom discussed where we pass a store to read from or nothing when nothing signifies that it is an in-memory store which makes the code confusing since it isn't obvious.

Comment (GabrielKS) [reply src/simulation/decision_model_simulation_results.jl:261]: So you'd like me to resolve the `store` to the in-memory store or not somewhere upstream so there's always a valid store getting passed around?

File: src/simulation/decision_model_simulation_results.jl (hunk 3 above)
Comment (daniel-thom) [reply src/simulation/decision_model_simulation_results.jl:91]: We’ve had this debate endlessly and have tried to use instances when possible because that’s what the Julia manual recommends. I may not be completely following the code, but don’t you have an instance for all cases where the user passed variables/duals/etc to load_results?

File: src/simulation/decision_model_simulation_results.jl (hunk 2 above)
Comment (daniel-thom) [reply src/simulation/decision_model_simulation_results.jl:261]: I’m not sure that I would change this, at least not here. `nothing` also means that the user didn’t pass a store.

File: src/simulation/decision_model_simulation_results.jl (hunk 3 above)
Comment (GabrielKS) [reply src/simulation/decision_model_simulation_results.jl:91]: Yeah, but consider the case where a user has loaded 2 time windows of a dual in their first call to `load_results!` and wants to load 3 time windows of a variable in their second call. Because the "what time periods do we have cached" information (`res.results_timestamps`) is across the whole results instance rather than per-variable/dual/etc., we have to now upgrade to 3 periods of that old dual. This requires fetching what duals we already have cached even if the user doesn't pass any new duals.

An alternative resolution would be allowing different variables/etc. to be cached to different numbers of time windows, and I'd be in support of that, but I was trying to limit the scope of this PR.

Comment (GabrielKS) [reply src/simulation/decision_model_simulation_results.jl:91]: Could I get a link to that section of the Julia manual? If this is a convention, it seems like one that needs to quite often be broken to avoid awkwardness, like we do with `get_components`.

Comment (jd-lara) [reply src/simulation/decision_model_simulation_results.jl:91]: @daniel-thom I think that was a preference for @kdheepak back in the day and not a hard rule

File: src/simulation/decision_model_simulation_results.jl (hunk 2 above)
Comment (jd-lara) [reply src/simulation/decision_model_simulation_results.jl:261]: what does not passing a store to get result mean? I don't think that is right

File: src/simulation/decision_model_simulation_results.jl (hunk 3 above)
Comment (jd-lara) [reply src/simulation/decision_model_simulation_results.jl:91]: Current guidance is captured here https://docs.julialang.org/en/v1/manual/types/#man-singleton-types

Comment (daniel-thom) [reply src/simulation/decision_model_simulation_results.jl:91]: I can’t remember and can try to look it up. I’m not saying it’s wrong to use types; clearly, we have to do that in get_components. I’m just saying that it you have an instance or can easily construct one, Julia prefers that you use it.

File: src/simulation/decision_model_simulation_results.jl (hunk 2 above)
Comment (daniel-thom) [reply src/simulation/decision_model_simulation_results.jl:261]: We could easily be talking around each other. There are many nuances here. The user can do either of these:
```
read_variable(results, “ActivePowerVariable__ThermalStandard”)
open_store(HdfSimulationStore, simulation_store_path, "r") do store
    read_variable(results, “ActivePowerVariable__ThermalStandard”; store=store)
end
```
In the first case we have to get the store, which could in memory or h5. If it’s h5, we have to open it. It’s in-memory, we can just use it. There is one slightly awkward case one line 288.

File: src/simulation/decision_model_simulation_results.jl (hunk 4 above)
Comment (GabrielKS) [reply src/simulation/decision_model_simulation_results.jl:293]: Sadly it cannot so easily because lots of existing code passes in arrays of `OptimizationContainerKey` even though they contain only one concrete type, but I'll work on finding a more elegant solution

File: src/simulation/decision_model_simulation_results.jl (hunk 5 above)
Comment (GabrielKS) [reply src/simulation/decision_model_simulation_results.jl:549]: Done

File: src/simulation/realized_meta.jl (hunk 1 above)
Comment (daniel-thom) [reply src/simulation/realized_meta.jl:72]: `_read_results` should only respond with the requested data. That’s a bug.

Comment (GabrielKS) [reply src/simulation/realized_meta.jl:72]: Okay, will fix

Comment (GabrielKS) [reply src/simulation/realized_meta.jl:72]: https://github.com/NREL-Sienna/PowerSimulations.jl/issues/1074

File: src/simulation/decision_model_simulation_results.jl (hunk 2 above)
Comment (jd-lara) [reply src/simulation/decision_model_simulation_results.jl:261]: no one does this 

```
open_store(HdfSimulationStore, simulation_store_path, "r") do store
    read_variable(results, “ActivePowerVariable__ThermalStandard”; store=store)
end
```

Assuming this patter will happen make the code way less understandable for developers. 

The most common way to access results is calling  `read_variables` or `read_realized_variables`

File: src/simulation/decision_model_simulation_results.jl (hunk 4 above)
Comment (GabrielKS) [reply src/simulation/decision_model_simulation_results.jl:293]: Done

**Comment by GabrielKS** [comment]
Now fixes #1074

File: src/simulation/decision_model_simulation_results.jl (hunk 2 above)
Comment (GabrielKS) [reply src/simulation/decision_model_simulation_results.jl:240]: In the absence of consensus, are we okay keeping `store::Union{Nothing, <:SimulationStore}` in this non-user-facing method for the moment?

Comment (daniel-thom) [reply src/simulation/decision_model_simulation_results.jl:240]: I’ll propose a patch in a separate PR.

File: src/simulation/decision_model_simulation_results.jl [hunk 6]
```diff
@@ -336,12 +269,24 @@ function _read_results(
     end
     existing_keys = list_result_keys(res, first(result_keys))
     _validate_keys(existing_keys, result_keys)
-    cached_results = get_cached_results(res, first(result_keys))
+    cached_results = get_cached_results(res, eltype(result_keys))
     if _are_results_cached(res, result_keys, timestamps, keys(cached_results))
-        @debug "reading results from SimulationsResults cache"
+        @debug "reading results from SimulationsResults cache"  # NOTE tests match on this
```
Comment (jd-lara) [inline src/simulation/decision_model_simulation_results.jl:274]: remove `# Note`

File: src/simulation/decision_model_simulation_results.jl [hunk 7]
```diff
@@ -336,12 +269,24 @@ function _read_results(
...
+            filtered_vals[result_key] = ResultsByTime{valtype(inner_converted), 1}(
+                result_data.key,
+                inner_converted,
+                result_data.resolution,
+                result_data.column_names)
+        end
+        return filtered_vals
     else
-        @debug "reading results from data store"
+        @debug "reading results from data store"  # NOTE tests match on this
```
Comment (jd-lara) [inline src/simulation/decision_model_simulation_results.jl:289]: remove  `# Note `

**Review by jd-lara — APPROVED** [review]
LGTM, good effort. Minor comments to remove unnecessary comments in the code base

File: src/simulation/decision_model_simulation_results.jl (hunk 6 above)
Comment (daniel-thom) [reply src/simulation/decision_model_simulation_results.jl:274]: As a developer I find this useful. It calls my attention to it.

**Review by daniel-thom — APPROVED** [review]
LGTM

File: src/simulation/decision_model_simulation_results.jl (hunk 6 above)
Comment (jd-lara) [reply src/simulation/decision_model_simulation_results.jl:274]: ok, lets leave it
